language: java
before_install:
  - pip install --user codecov
dist: bionic
addons:
  apt:
    packages:
      - ant-optional
service:
  - xvfb
script: xvfb-run -e /dev/stdout -a ant test
notifications:
  irc:
    channels:
      - "irc.libera.chat#polanieonline"
      - "irc.libera.chat#polanieonline-devel"
    on_success: change
    on_failure: change
    use_notice: false
    skip_join: false
after_success:
  - codecov
